services:
  frontend:
    image: siddique7/ecommerce-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

backend:
  build: ./backend
  ports:
    - "5000:5000"
  env_file:
    - ./backend/.env
  depends_on:
    - mongo

  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: